<a href="https://colab.research.google.com/github/jeffheaton/app_deep_learning/blob/main/t81_558_class_02_3_pandas_grouping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="In Colab öffnen"/></a>

# T81-558: Anwendungen tiefer neuronaler Netzwerke

**Modul 2: Python für maschinelles Lernen**

- Dozent: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Jeff Heaton](https://sites.wustl.edu/jeffheaton/)
– Weitere Informationen finden Sie unter [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Modul 2 Material

Hauptvideovorlesung:

- Teil 2.1: Einführung in Pandas [[Video]](https://www.youtube.com/watch?v=wixHCvnvnsU&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=wixHCvnvnsU&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.2: Kategorische Werte [[Video]](https://www.youtube.com/watch?v=Fm7Ax23hDP0&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=Fm7Ax23hDP0&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- **Teil 2.3: Gruppieren, Sortieren und Mischen in Python Pandas** [[Video]](https://www.youtube.com/watch?v=tUhaD8xWd7k&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=tUhaD8xWd7k&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.4: Verwenden von Apply und Map in Pandas [[Video]](https://www.youtube.com/watch?v=YNo_mg1RrkM&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=YNo_mg1RrkM&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.5: Feature Engineering in Pandas für Deep Learning in PyTorch [[Video]](https://www.youtube.com/watch?v=ezaVtM405Qs&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=ezaVtM405Qs&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)

# Google CoLab-Anweisungen

Der folgende Code stellt sicher, dass Google CoLab die richtige Version von TensorFlow ausführt.

In [1]:
try:
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: using Google CoLab

# Teil 2.3: Gruppieren, Sortieren und Mischen

Wir werden uns einige Möglichkeiten ansehen, wie wir einen gesamten Pandas-Datenrahmen beeinflussen können. Mit diesen Techniken können wir Datensätze gruppieren, sortieren und mischen. Dies sind alles wichtige Vorgänge sowohl für die Vorverarbeitung als auch für die Auswertung von Daten.

## Einen Datensatz neu mischen

Möglicherweise verbergen sich in der Reihenfolge der Zeilen Ihres Datensatzes Informationen. Sofern Sie nicht mit Zeitreihendaten arbeiten, sollte die Reihenfolge der Zeilen nicht von Bedeutung sein. Überlegen Sie, ob Ihr Trainingssatz Mitarbeiter eines Unternehmens enthält. Vielleicht ist dieser Datensatz nach der Anzahl der Jahre sortiert, die die Mitarbeiter im Unternehmen beschäftigt waren. Es ist in Ordnung, eine einzelne Spalte zu haben, die die Dienstjahre angibt. Die Daten in dieser Reihenfolge anzuordnen, könnte jedoch problematisch sein.

Überlegen Sie, ob Sie die Daten in Training und Validierung aufteilen würden. Am Ende könnte Ihr Validierungssatz nur die neueren Mitarbeiter und der Trainingssatz die längerfristig beschäftigten Mitarbeiter enthalten. Das Aufteilen der Daten in eine k-fache Kreuzvalidierung könnte ähnliche Probleme mit sich bringen. Aus diesem Grund ist es wichtig, den Datensatz neu zu mischen.

Oft werden das Mischen und die Neuindizierung zusammen durchgeführt. Das Mischen randomisiert die Reihenfolge des Datensatzes. Die Zeilennummern von Pandas werden dadurch jedoch nicht geändert. Der folgende Code demonstriert eine Neumischung. Beachten Sie, dass das Programm die erste Spalte der Zeilenindizes nicht zurückgesetzt hat. Im Allgemeinen verursacht dies keine Probleme und ermöglicht die Rückverfolgung zur ursprünglichen Reihenfolge der Daten. Normalerweise ziehe ich es jedoch vor, diesen Index zurückzusetzen. Ich begründe dies damit, dass mir die Anfangsposition normalerweise egal ist und es einige Fälle gibt, in denen dieser ungeordnete Index Probleme verursachen kann.

In [2]:
import numpy as np
import pandas as pd

df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

# np.random.seed(42) # Entfernen Sie das Kommentarzeichen aus dieser Zeile, um jedes Mal die gleiche Reihenfolge zu erhalten.
df = df.reindex(np.random.permutation(df.index))

set_option("display.max_columns", 7)
set_option("display.max_rows", 5)
display(df)

,mpg,cylinders,displacement,...,year,origin,name
112,19.0,4,122.0,...,73,1,ford pinto
291,19.2,8,267.0,...,79,1,chevrolet malibu classic (sw)
...,...,...,...,...,...,...,...
200,18.0,6,250.0,...,76,1,ford granada ghia
287,16.5,8,351.0,...,79,1,mercury grand marquis

Der folgende Code demonstriert eine Neuindizierung. Beachten Sie, wie die Neuindizierung die Zeilenindizes sortiert.

In [3]:
set_option("display.max_columns", 7)
set_option("display.max_rows", 5)

df.reset_index(inplace=True, drop=True)
display(df)

,mpg,cylinders,displacement,...,year,origin,name
0,19.0,4,122.0,...,73,1,ford pinto
1,19.2,8,267.0,...,79,1,chevrolet malibu classic (sw)
...,...,...,...,...,...,...,...
396,18.0,6,250.0,...,76,1,ford granada ghia
397,16.5,8,351.0,...,79,1,mercury grand marquis

### Sortieren eines Datensatzes

Während es immer gut ist, einen Datensatz vor dem Training neu zu mischen, möchten Sie den Datensatz während des Trainings und der Vorverarbeitung möglicherweise auch sortieren. Durch das Sortieren des Datensatzes können Sie die Zeilen für eine oder mehrere Spalten entweder aufsteigend oder absteigend sortieren. Der folgende Code sortiert den MPG-Datensatz nach Namen und zeigt das erste Auto an.

In [4]:
df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

df = df.sort_values(by="name", ascending=True)
print(f"Das erste Auto ist: {df['name'].iloc[0]}")

set_option("display.max_columns", 7)
set_option("display.max_rows", 5)
display(df)

The first car is: amc ambassador brougham

      mpg  cylinders  displacement  ...  year  origin                     name
96   13.0          8         360.0  ...    73       1  amc ambassador brougham
9    15.0          8         390.0  ...    70       1       amc ambassador dpl
..    ...        ...           ...  ...   ...     ...                      ...
325  44.3          4          90.0  ...    80       2     vw rabbit c (diesel)
293  31.9          4          89.0  ...    79       2         vw rabbit custom

[398 rows x 9 columns]

### Gruppieren eines Datensatzes

Gruppieren ist eine typische Operation für Datensätze. In der Structured Query Language (SQL) wird diese Operation als „GROUP BY“ bezeichnet. Programmierer verwenden Gruppieren, um Daten zusammenzufassen. Dadurch verringert sich die Anzahl der zusammengefassten Zeilen normalerweise, und Sie können die Gruppierung nicht rückgängig machen. Aufgrund dieses Informationsverlusts ist es wichtig, die Originaldaten vor der Gruppierung beizubehalten.

Wir verwenden den Auto MPG-Datensatz, um die Gruppierung zu demonstrieren.

In [5]:
df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

set_option("display.max_columns", 7)
set_option("display.max_rows", 5)
display(df)

,mpg,cylinders,displacement,...,year,origin,name
0,18.0,8,307.0,...,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,...,70,1,buick skylark 320
...,...,...,...,...,...,...,...
396,28.0,4,120.0,...,82,1,ford ranger
397,31.0,4,119.0,...,82,1,chevy s-10

Sie können den obigen Datensatz mit der Gruppe verwenden, um Zusammenfassungen durchzuführen. Der folgende Code gruppiert beispielsweise Zylinder nach dem Durchschnitt (Mittelwert). Dieser Code stellt die Gruppierung bereit. Zusätzlich zu **mean** können Sie andere Aggregatfunktionen verwenden, z. B. **sum** oder **count**.

In [6]:
g = df.groupby("cylinders")["mpg"].mean()
g

cylinders
3    20.550000
4    29.286765
5    27.366667
6    19.985714
8    14.963107
Name: mpg, dtype: float64

Es könnte nützlich sein, diese **Durchschnittswerte** als Wörterbuch zu haben.

In [7]:
d = g.to_dict()
d

{3: 20.55,
 4: 29.28676470588235,
 5: 27.366666666666664,
 6: 19.985714285714284,
 8: 14.963106796116506}

Mit einem Wörterbuch können Sie schnell auf ein einzelnes Element zugreifen. Sie können beispielsweise schnell den Mittelwert für Sechszylinderautos nachschlagen. Sie werden sehen, dass die ZielKodierung, die später in diesem Modul vorgestellt wird, diese Technik verwendet.

In [8]:
d[6]

19.985714285714284

Der folgende Code zeigt, wie die Anzahl der Zeilen gezählt wird, die der jeweiligen Zylinderanzahl entsprechen.

In [9]:
df.groupby("cylinders")["mpg"].count().to_dict()

{3: 4, 4: 204, 5: 3, 6: 84, 8: 103}