<a href="https://colab.research.google.com/github/jeffheaton/app_deep_learning/blob/main/t81_558_class_02_1_python_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="In Colab öffnen"/></a>

# T81-558: Anwendungen tiefer neuronaler Netzwerke

**Modul 2: Python für maschinelles Lernen**

- Dozent: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Jeff Heaton](https://sites.wustl.edu/jeffheaton/)
– Weitere Informationen finden Sie unter [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Modul 2 Material

Hauptvideovorlesung:

- **Teil 2.1: Einführung in Pandas** [[Video]](https://www.youtube.com/watch?v=wixHCvnvnsU&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=wixHCvnvnsU&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.2: Kategorische Werte [[Video]](https://www.youtube.com/watch?v=Fm7Ax23hDP0&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=Fm7Ax23hDP0&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.3: Gruppieren, Sortieren und Mischen in Python Pandas [[Video]](https://www.youtube.com/watch?v=tUhaD8xWd7k&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=tUhaD8xWd7k&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.4: Verwenden von Apply und Map in Pandas [[Video]](https://www.youtube.com/watch?v=YNo_mg1RrkM&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=YNo_mg1RrkM&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.5: Feature Engineering in Pandas für Deep Learning in PyTorch [[Video]](https://www.youtube.com/watch?v=ezaVtM405Qs&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=ezaVtM405Qs&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)

# Google CoLab-Anweisungen

Der folgende Code stellt sicher, dass Google CoLab ausgeführt wird und bildet bei Bedarf Google Drive ab.

In [1]:
try:
    from google.colab import drive

    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: using Google CoLab

# Teil 2.1: Einführung in Pandas

[Pandas](http://pandas.pydata.org/) ist eine Open-Source-Bibliothek, die leistungsstarke, benutzerfreundliche Datenstrukturen und Datenanalysetools für die Programmiersprache Python bereitstellt. Sie basiert auf dem [Pandas](http://pandas.pydata.org/)-Konzept, das in [Pandas](http://pandas.pydata.org/) zu finden ist. Für diese Klasse werden Pandas das primäre Mittel sein, mit dem wir Daten manipulieren, die von neuronalen Netzwerken verarbeitet werden sollen.

Der Datenrahmen ist eine entscheidende Komponente von Pandas. Wir werden ihn verwenden, um auf [auto-mpg dataset](https://archive.ics.uci.edu/ml/datasets/Auto+MPG) zuzugreifen. Sie finden diesen Datensatz im UCI-Repository für maschinelles Lernen. Für diesen Kurs verwenden wir eine Version des Auto MPG-Datensatzes, dem ich Spaltenüberschriften hinzugefügt habe. Sie finden meinen [auto-mpg dataset](https://archive.ics.uci.edu/ml/datasets/Auto+MPG) unter [auto-mpg dataset](https://archive.ics.uci.edu/ml/datasets/Auto+MPG).

UCI hat diesen Datensatz aus der StatLib-Bibliothek entnommen, die von der Carnegie Mellon University verwaltet wird. Der Datensatz wurde 1983 auf der American Statistical Association Exposition verwendet. Er enthält Daten für 398 Autos, darunter [mpg](https://en.wikipedia.org/wiki/Fuel_economy_in_automobiles), [mpg](https://en.wikipedia.org/wiki/Fuel_economy_in_automobiles)>), [mpg](https://en.wikipedia.org/wiki/Fuel_economy_in_automobiles), [mpg](https://en.wikipedia.org/wiki/Fuel_economy_in_automobiles) , Gewicht, Beschleunigung, Modelljahr, Herkunft und den Namen des Autos.

Der folgende Code lädt den MPG-Datensatz in einen Datenrahmen:

In [2]:
# Einfacher Datenrahmen
import pandas as pd

set_option("display.max_columns", 7)
df = read_csv("https://data.heatonresearch.com/data/t81-558/auto-mpg.csv")
display(df[0:5])

    mpg  cylinders  displacement  ... year  origin                       name
0  18.0          8         307.0  ...   70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...   70       1          buick skylark 320
2  18.0          8         318.0  ...   70       1         plymouth satellite
3  16.0          8         304.0  ...   70       1              amc rebel sst
4  17.0          8         302.0  ...   70       1                ford torino

[5 rows x 9 columns]

Die **display**-Funktion bietet eine übersichtlichere Anzeige als das bloße Drucken des Datenrahmens. Durch die Angabe der maximalen Zeilen und Spalten können Sie die Anzeige besser steuern.

In [3]:
set_option("display.max_columns", 7)
set_option("display.max_rows", 5)
display(df)

,mpg,cylinders,displacement,...,year,origin,name
0,18.0,8,307.0,...,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,...,70,1,buick skylark 320
...,...,...,...,...,...,...,...
396,28.0,4,120.0,...,82,1,ford ranger
397,31.0,4,119.0,...,82,1,chevy s-10

Es ist möglich, einen zweiten Datenrahmen zu generieren, um statistische Informationen zum ersten Datenrahmen anzuzeigen.

In [4]:
# Nicht numerische Zeichen entfernen
df = df.select_dtypes(include=["int", "float"])

headers = list(df.columns.values)
fields = []

for field in headers:
    fields.append(
        {
            "name": field,
            "mean": df[field].mean(),
            "var": df[field].var(),
            "sdev": df[field].std(),
        }
    )

for field in fields:
    print(field)

{'name': 'mpg', 'mean': 23.514572864321607, 'var': 61.089610774274405, 'sdev': 7.815984312565782}
{'name': 'cylinders', 'mean': 5.454773869346734, 'var': 2.893415439920003, 'sdev': 1.7010042445332119}
{'name': 'displacement', 'mean': 193.42587939698493, 'var': 10872.199152247384, 'sdev': 104.26983817119591}
{'name': 'weight', 'mean': 2970.424623115578, 'var': 717140.9905256763, 'sdev': 846.8417741973268}
{'name': 'acceleration', 'mean': 15.568090452261307, 'var': 7.604848233611383, 'sdev': 2.757688929812676}
{'name': 'year', 'mean': 76.01005025125629, 'var': 13.672442818627143, 'sdev': 3.697626646732623}
{'name': 'origin', 'mean': 1.5728643216080402, 'var': 0.6432920268850549, 'sdev': 0.8020548777266148}

Dieser Code gibt eine Liste von Wörterbüchern aus, die diese statistischen Informationen enthalten. Diese Informationen ähneln dem JSON-Code in Modul 1. Wenn korrektes JSON benötigt wird, sollte das Programm diese Datensätze zu einer Liste hinzufügen und den Befehl **dumps** der Python-JSON-Bibliothek aufrufen.

Das Python-Programm kann diese JSON-ähnlichen Informationen zur besseren Anzeige in einen Datenrahmen umwandeln.

In [5]:
set_option("display.max_columns", 0)
set_option("display.max_rows", 0)
df2 = DataFrame(fields)
display(df2)

           name         mean            var        sdev
0           mpg    23.514573      61.089611    7.815984
1     cylinders     5.454774       2.893415    1.701004
2  displacement   193.425879   10872.199152  104.269838
3        weight  2970.424623  717140.990526  846.841774
4  acceleration    15.568090       7.604848    2.757689
5          year    76.010050      13.672443    3.697627
6        origin     1.572864       0.643292    0.802055

## Fehlende Werte

Fehlende Werte sind eine Realität des maschinellen Lernens. Im Idealfall enthält jede Datenzeile Werte für alle Spalten. Dies ist jedoch selten der Fall. Die meisten Werte sind in der MPG-Datenbank vorhanden. In der PS-Spalte fehlen jedoch Werte. Eine gängige Vorgehensweise besteht darin, fehlende Werte durch den Medianwert für diese Spalte zu ersetzen. Das Programm berechnet [median](https://en.wikipedia.org/wiki/Median). Der folgende Code ersetzt alle NA-Werte in PS durch den Medianwert:

In [6]:
df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)
print(f"PS hat n/a? {isnull(df['horsepower']).values.any()}")

print("Filling missing values...")
med = df["horsepower"].median()
df["horsepower"] = df["horsepower"].fillna(med)
# df = df.dropna() # Sie können NA-Werte auch einfach löschen

print(f"PS hat n/a? {isnull(df['horsepower']).values.any()}")

horsepower has na? True
Filling missing values...
horsepower has na? False

## Umgang mit Ausreißern

Ausreißer sind Werte, die ungewöhnlich hoch oder niedrig sind. Wir betrachten Ausreißer normalerweise als Werte, die mehrere Standardabweichungen vom Mittelwert entfernt sind. Manchmal sind Ausreißer einfach Fehler; dies ist ein Ergebnis von [observation error](https://en.wikipedia.org/wiki/Observational_error). Ausreißer können auch wirklich große oder kleine Werte sein, die möglicherweise schwer zu beheben sind. Die folgende Funktion kann solche Werte entfernen.

In [7]:
# Entfernen Sie alle Zeilen, bei denen die angegebene Spalte +/- SD-Standardabweichungen beträgt
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)

Der folgende Code löscht alle Zeilen aus dem Auto-MPG-Datensatz, bei denen die Leistung zwei oder mehr Standardabweichungen über oder unter dem Mittelwert liegt.

In [8]:
import numpy as np


df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

# Merkmalsvektor erstellen
med = df["horsepower"].median()
df["horsepower"] = df["horsepower"].fillna(med)

# Löschen der Namensspalte
df.drop("name", 1, inplace=True)

# Ausreißer in der Leistung eliminieren
print("Length before MPG outliers dropped: {}".format(len(df)))
remove_outliers(df, "mpg", 2)
print("Length after MPG outliers dropped: {}".format(len(df)))

set_option("display.max_columns", 0)
set_option("display.max_rows", 5)
display(df)

Length before MPG outliers dropped: 398
Length after MPG outliers dropped: 388

<ipython-input-8-66622ca5b2b3>:13: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df.drop("name", 1, inplace=True)

      mpg  cylinders  displacement  ...  acceleration  year  origin
0    18.0          8         307.0  ...          12.0    70       1
1    15.0          8         350.0  ...          11.5    70       1
..    ...        ...           ...  ...           ...   ...     ...
396  28.0          4         120.0  ...          18.6    82       1
397  31.0          4         119.0  ...          19.4    82       1

[388 rows x 8 columns]

## Felder löschen

Sie müssen Felder löschen, die für das neuronale Netzwerk keinen Wert haben. Der folgende Code entfernt die Spalte „Name“ aus dem MPG-Datensatz.

In [9]:
df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

print(f"Vor dem Löschen: {list(df.columns)}")
df.drop("name", 1, inplace=True)
print(f"Nach dem Löschen: {list(df.columns)}")

Before drop: ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'year', 'origin', 'name']
After drop: ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'year', 'origin']

<ipython-input-9-4af43aae8a9c>:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df.drop("name", 1, inplace=True)

## Verketten von Zeilen und Spalten

Python kann Zeilen und Spalten miteinander verketten, um neue Datenrahmen zu bilden. Der folgende Code erstellt einen neuen Datenrahmen aus den Spalten **Name** und **Horsepower** des Auto MPG-Datensatzes. Das Programm tut dies, indem es zwei Spalten miteinander verkettet.

In [10]:
# Erstellen Sie einen neuen Datenrahmen aus Name und Leistung

df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

col_horsepower = df["horsepower"]
col_name = df["name"]
result = concat([col_name, col_horsepower], axis=1)

set_option("display.max_columns", 0)
set_option("display.max_rows", 5)
display(result)

                          name  horsepower
0    chevrolet chevelle malibu       130.0
1            buick skylark 320       165.0
..                         ...         ...
396                ford ranger        79.0
397                 chevy s-10        82.0

[398 rows x 2 columns]

Die Funktion **concat** kann auch Zeilen miteinander verketten. Dieser Code verkettet die ersten beiden Zeilen und die letzten beiden Zeilen des Auto MPG-Datensatzes.

In [11]:
# Erstellen Sie einen neuen Datenrahmen aus den ersten beiden Zeilen und den letzten beiden Zeilen

df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

result = concat([df[0:2], df[-2:]], axis=0)

set_option("display.max_columns", 7)
set_option("display.max_rows", 0)
display(result)

,mpg,cylinders,displacement,...,year,origin,name
0,18.0,8,307.0,...,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,...,70,1,buick skylark 320
396,28.0,4,120.0,...,82,1,ford ranger
397,31.0,4,119.0,...,82,1,chevy s-10

## Training und Validierung

Wir müssen ein maschinelles Lernmodell anhand seiner Fähigkeit bewerten, Werte vorherzusagen, die es noch nie zuvor gesehen hat. Aus diesem Grund teilen wir die Trainingsdaten häufig in einen Validierungs- und einen Trainingssatz auf. Das maschinelle Lernmodell lernt aus den Trainingsdaten, wird aber letztendlich auf der Grundlage der Validierungsdaten bewertet.

- **Trainingsdaten** - **In Beispieldaten** – Die Daten, die das neuronale Netzwerk zum Trainieren verwendet hat.
- **Validierungsdaten** – **Out-of-Sample-Daten** – Die Daten, anhand derer das maschinelle Lernmodell ausgewertet wird, nachdem es an die Trainingsdaten angepasst wurde.

Es gibt zwei effektive Möglichkeiten, mit Trainings- und Validierungsdaten umzugehen:

- **Training/Validierung-Aufteilung** - Das Programm teilt die Daten nach einem bestimmten Verhältnis zwischen einem Trainings- und einem Validierungssatz (Hold-out) auf. Typische Raten sind 80 % Training und 20 % Validierung.
- **K-fach-Kreuzvalidierung** - Das Programm teilt die Daten in mehrere Faltungen und Modelle auf. Da das Programm die gleiche Anzahl an Modellen wie Faltungen erstellt, kann das Programm Out-of-Sample-Vorhersagen für den gesamten Datensatz generieren.

Der folgende Code teilt die MPG-Daten in einen Trainings- und einen Validierungssatz auf. Der Trainingssatz verwendet 80 % der Daten und der Validierungssatz 20 %. Abbildung 2.TRN-VAL zeigt, wie wir ein Modell mit 80 % der Daten trainieren und es dann anhand der verbleibenden 20 % validieren.

**Abbildung 2.TRN-VAL: Training und Validierung**
![Training and Validation](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_1_train_val.png "Training and Validation")

In [12]:
df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

# Normalerweise ist es eine gute Idee, zu mischen
df = df.reindex(np.random.permutation(df.index))

mask = np.random.rand(len(df)) < 0.8
trainDF = DataFrame(df[mask])
validationDF = DataFrame(df[~mask])

print(f"Trainings-DF: {len(trainDF)}")
print(f"Validierungs-DF: {len(validationDF)}")

Training DF: 314
Validation DF: 84

## Konvertieren eines Dataframes in eine Matrix

Neuronale Netzwerke arbeiten nicht direkt mit Python-Datenrahmen. Ein neuronales Netzwerk erfordert eine numerische Matrix. Das Programm verwendet die **values**-Eigenschaft eines Datenrahmens, um die Daten in eine Matrix umzuwandeln.

In [13]:
df.values

array([[15.0, 8, 429.0, ..., 70, 1, 'ford galaxie 500'],
       [25.8, 4, 156.0, ..., 81, 1, 'dodge aries wagon (sw)'],
       [13.0, 8, 350.0, ..., 76, 1, 'chevy c10'],
       ...,
       [17.5, 6, 258.0, ..., 76, 1, 'amc pacer d/l'],
       [15.0, 8, 350.0, ..., 75, 1, 'chevrolet bel air'],
       [30.0, 4, 146.0, ..., 80, 2, 'mercedes-benz 240d']], dtype=object)

Möglicherweise möchten Sie nur einige der Spalten konvertieren und die Spalte „Name“ weglassen. Verwenden Sie dazu den folgenden Code.

In [14]:
df[
    [
        "mpg",
        "cylinders",
        "displacement",
        "horsepower",
        "weight",
        "acceleration",
        "year",
        "origin",
    ]
].values

array([[ 15. ,   8. , 429. , ...,  10. ,  70. ,   1. ],
       [ 25.8,   4. , 156. , ...,  14.4,  81. ,   1. ],
       [ 13. ,   8. , 350. , ...,  12. ,  76. ,   1. ],
       ...,
       [ 17.5,   6. , 258. , ...,  17.8,  76. ,   1. ],
       [ 15. ,   8. , 350. , ...,  14. ,  75. ,   1. ],
       [ 30. ,   4. , 146. , ...,  21.8,  80. ,   2. ]])

## Speichern eines Dataframes als CSV

Viele der Aufgaben in diesem Kurs erfordern, dass Sie einen Datenrahmen speichern, um ihn dem Kursleiter vorzulegen. Der folgende Code führt eine Neuordnung durch und speichert dann eine neue Kopie.

In [15]:
import os
import numpy as np

path = "."

df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

filename_write = os.path.join(path, "auto-mpg-shuffle.csv")
df = df.reindex(np.random.permutation(df.index))
# Geben Sie „index = false“ an, um die Zeilennummern nicht zu schreiben.
df.to_csv(filename_write, index=False)

## Speichern eines Dataframes in Pickle

Eine Vielzahl von Softwareprogrammen kann als CSV gespeicherte Textdateien verwenden. Allerdings dauert ihre Generierung länger und bei der Konvertierung kann manchmal etwas an Genauigkeit verloren gehen. Im Allgemeinen werden Sie im CSV-Format ausgeben, da es sehr kompatibel ist, auch außerhalb von Python. Ein anderes Format ist [Pickle](https://docs.python.org/3/library/pickle.html). Der folgende Code speichert den Dataframe in Pickle. Pickle speichert Daten in der exakten Binärdarstellung, die von Python verwendet wird. Der Vorteil ist, dass beim Wechsel ins CSV-Format keine Daten verloren gehen. Der Nachteil ist, dass im Allgemeinen nur Python-Programme Pickle-Dateien lesen können.

In [16]:
import os
import pickle

path = "."

df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

filename_write = os.path.join(path, "auto-mpg-shuffle.pkl")
df = df.reindex(np.random.permutation(df.index))

with open(filename_write, "wb") as fp:
    pickle.dump(df, fp)

Das Zurückladen der Pickle-Datei in den Speicher erfolgt mit den folgenden Codezeilen. Beachten Sie, dass die Indexnummern vom vorherigen Mischen immer noch durcheinander sind? Beim Laden der neu erstellten CSV-Datei (im letzten Schritt) wurden diese Werte nicht beibehalten.

In [17]:
import os
import pickle

path = "."

df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

filename_read = os.path.join(path, "auto-mpg-shuffle.pkl")

with open(filename_write, "rb") as fp:
    df = pickle.load(fp)

set_option("display.max_columns", 7)
set_option("display.max_rows", 5)
display(df)

      mpg  cylinders  displacement  ...  year  origin                    name
191  22.0          6         225.0  ...    76       1        plymouth valiant
287  16.5          8         351.0  ...    79       1   mercury grand marquis
..    ...        ...           ...  ...   ...     ...                     ...
70   13.0          8         400.0  ...    72       1  chrysler newport royal
337  32.4          4         107.0  ...    80       3            honda accord

[398 rows x 9 columns]

# Modul 2 Aufgabe

Die zweite Aufgabe finden Sie hier: [assignment 2](https://github.com/jeffheaton/app_deep_learning/blob/main/assignments/assignment_yourname_t81_558_class2.ipynb)